---
- name: flannel config
  template: src=../templates/options.env.j2 dest=/etc/flannel/options.env
- name: flannel systemd
  template: src=../templates/40-ExecStartPre-symlink.conf.j2 dest=/etc/systemd/system/flanneld.service.d/40-ExecStartPre-symlink.conf
- name: flannel systemd (2)
  template: src=../templates/40-flannel.conf.j2 dest=/etc/systemd/system/docker.service.d/40-flannel.conf
